defaults:
  - model: null # set to null here so it can be overrided in a particular experiment.

_target_: src.models.ImportanceSamplingModel_nlp.ImportanceSamplingModel
percent_train: 0.1
weight_decay: 0.01
